# Generated by Django 4.2.4 on 2024-02-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='logos/')),
                ('image1', models.ImageField(upload_to='Advertising/')),
                ('image2', models.ImageField(upload_to='Advertising/')),
                ('image3', models.ImageField(upload_to='Advertising/')),
                ('brand_strategy', models.TextField()),
                ('product_experience', models.TextField()),
                ('time_management', models.TextField()),
                ('beautiful_design', models.TextField()),
                ('short_about_us', models.TextField()),
                ('about_us_description', models.TextField()),
                ('pic1', models.ImageField(upload_to='Advertising/')),
                ('pic2', models.ImageField(upload_to='Advertising/')),
                ('title_service1', models.CharField(max_length=255)),
                ('description_title_service1', models.TextField()),
                ('title_service2', models.CharField(max_length=255)),
                ('description_title_service2', models.TextField()),
                ('title_service3', models.CharField(max_length=255)),
                ('description_title_service3', models.TextField()),
                ('slogan', models.CharField(max_length=255)),
                ('cover_pic', models.ImageField(upload_to='Advertising/')),
                ('description', models.TextField()),
                ('video_url', models.URLField()),
                ('title_1', models.CharField(max_length=255)),
                ('pic_1', models.ImageField(upload_to='Advertising/')),
                ('description_1', models.TextField()),
                ('title_2', models.CharField(max_length=255)),
                ('pic_2', models.ImageField(upload_to='Advertising/')),
                ('description_2', models.TextField()),
                ('title_3', models.CharField(max_length=255)),
                ('pic_3', models.ImageField(upload_to='Advertising/')),
                ('description_3', models.TextField()),
                ('title_4', models.CharField(max_length=255)),
                ('pic_4', models.ImageField(upload_to='Advertising/')),
                ('description_4', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
