# Generated by Django 4.2.4 on 2024-02-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0003_advertising_youtube_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='Companyname',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
