# Generated by Django 5.0.2 on 2024-02-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0004_advertising_companyname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oursites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('developer', models.CharField(max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('image1', models.ImageField(upload_to='Oursite/')),
                ('image2', models.ImageField(upload_to='Oursite/')),
                ('description1', models.TextField(null=True)),
                ('description2', models.TextField(null=True)),
                ('summery', models.TextField(null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Oursite', to='DynamicGenerator.category')),
            ],
        ),
    ]
