# Generated by Django 5.0.2 on 2024-02-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0005_oursites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oursites',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
