# Generated by Django 5.0.2 on 2024-02-23 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0006_alter_oursites_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oursites',
            name='previewurl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oursites',
            name='date',
            field=models.DateField(),
        ),
    ]
