# Generated by Django 5.0.2 on 2024-02-23 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0007_oursites_previewurl_alter_oursites_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='oursites',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
