# Generated by Django 5.0.2 on 2024-03-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0009_sitepurchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='short_about_us2',
            field=models.TextField(null=True),
        ),
    ]
