# Generated by Django 5.0.2 on 2024-03-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0012_alter_advertising_category_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Foutrth_Service',
            new_name='Fourth_Service',
        ),
    ]
