# Generated by Django 5.0.2 on 2024-03-22 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0015_portfolio_linked_in_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='Linked_In_link',
            new_name='linkedin_link',
        ),
    ]
