# Generated by Django 5.0.2 on 2024-03-23 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0016_rename_linked_in_link_portfolio_linkedin_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Portfolio', to='DynamicGenerator.category'),
        ),
    ]
