# Generated by Django 5.0.2 on 2024-03-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0018_remove_advertising_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='commession',
            field=models.IntegerField(default=0),
        ),
    ]
