# Generated by Django 5.0.2 on 2024-03-25 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0020_withdrawl_request'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawl_request',
            options={'verbose_name_plural': 'Withdraw Request'},
        ),
    ]
