# Generated by Django 5.0.2 on 2024-03-25 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0021_alter_withdrawl_request_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='withdrawl_request',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'Withdraw Request'},
        ),
        migrations.AlterField(
            model_name='withdrawl_request',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
