# Generated by Django 5.0.2 on 2024-03-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0022_alter_withdrawl_request_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawl_request',
            name='bank',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='withdrawl_request',
            name='routing_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
