# Generated by Django 5.0.2 on 2024-03-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0026_alter_oursites_options_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oursites',
            options={'verbose_name_plural': 'SoftBit Sites'},
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='item',
            new_name='site',
        ),
        migrations.RemoveField(
            model_name='oursites',
            name='previewurl',
        ),
    ]
