# Generated by Django 5.0.2 on 2024-03-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0031_deployerate_deploye'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployerate',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
