# Generated by Django 5.0.2 on 2024-03-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0035_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertising',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Advertising', to='DynamicGenerator.category'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Portfoilo', to='DynamicGenerator.category'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='profilepic/118075335_744109276133549_1110864460278063364_n_c253ba2d-0077-40bc-82e3-372b_oJqMKqo.webp', null=True, upload_to='profilepic/'),
        ),
    ]
