# Generated by Django 5.0.2 on 2024-04-07 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0036_advertising_category_portfolio_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertising',
            name='category',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='category',
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Logo', models.ImageField(upload_to='hospital_logos/')),
                ('Slogan', models.CharField(max_length=255)),
                ('Short_Intro', models.TextField()),
                ('Doctors', models.PositiveIntegerField()),
                ('Patient_Beds', models.PositiveIntegerField()),
                ('Health_Programs', models.TextField()),
                ('Whats_App_Number', models.CharField(max_length=20)),
                ('Video', models.URLField()),
                ('Service_Slogan', models.CharField(max_length=255)),
                ('Detail_About_Service', models.TextField()),
                ('General_Care_Image', models.ImageField(upload_to='hospital_images/')),
                ('General_Care_Info', models.TextField()),
                ('Pediatric_Care_Image', models.ImageField(upload_to='hospital_images/')),
                ('Pediatric_Care_Info', models.TextField()),
                ('Neurology_Image', models.ImageField(upload_to='hospital_images/')),
                ('Neurology_Info', models.TextField()),
                ('Womens_Health_Image', models.ImageField(upload_to='hospital_images/')),
                ('Womens_Health_Service_Info', models.TextField()),
                ('Emergency_Care_Image', models.ImageField(upload_to='hospital_images/')),
                ('Emergency_Care_Info', models.TextField()),
                ('Laboratory_Image', models.ImageField(upload_to='hospital_images/')),
                ('Laboratory_Info', models.TextField()),
                ('About_Treatments', models.TextField()),
                ('First_Pediatrics_Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('First_Pediatrics_Doctor_Name', models.CharField(max_length=255)),
                ('First_Pediatrics_Doctor_Expertise', models.CharField(max_length=255)),
                ('Second_Pediatrics_Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('Second_Pediatrics_Doctor_Name', models.CharField(max_length=255)),
                ('Second_Pediatrics_Doctor_Expertise', models.CharField(max_length=255)),
                ('Neurology_Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('Neurology_Doctor_Name', models.CharField(max_length=255)),
                ('Neurology_Doctor_Expertise', models.CharField(max_length=255)),
                ('Advanced_Diagnostic_Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('Advanced_Diagnostic_Doctor_Name', models.CharField(max_length=255)),
                ('Advanced_Diagnostic_Doctor_Expertise', models.CharField(max_length=255)),
                ('Rapid_Response_Experts_Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('Rapid_Response_Experts_Doctor_Name', models.CharField(max_length=255)),
                ('Rapid_Response_Experts_Doctor_Expertise', models.CharField(max_length=255)),
                ('Hospital_Image', models.ImageField(upload_to='hospital_images/')),
                ('Hospital_Address', models.TextField()),
                ('Laboratory_Name', models.CharField(max_length=255)),
                ('Monday_to_Friday', models.CharField(max_length=50)),
                ('Saturday_Timing', models.CharField(max_length=50)),
                ('Sunday_Timing', models.CharField(max_length=50)),
                ('Laboratory_Address', models.TextField()),
                ('Laboratory_Video', models.URLField()),
                ('Patient_Image', models.ImageField(upload_to='patient_images/')),
                ('Doctor_Image', models.ImageField(upload_to='doctor_images/')),
                ('Question1_Accept_Insurance_Policy', models.BooleanField(default=False)),
                ('Question2_Is_Emergency_Unit_Available', models.BooleanField(default=False)),
                ('Question3_Provide_Telehealth_Health', models.BooleanField(default=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Youtube', models.URLField()),
                ('Facebook', models.URLField()),
                ('LinkedIn', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Hospital', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
