# Generated by Django 5.0.2 on 2024-04-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0037_remove_advertising_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='Video',
            field=models.FileField(null=True, upload_to='hospital_videos/'),
        ),
    ]
