# Generated by Django 5.0.2 on 2024-04-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0040_remove_sitepurchase_duration_days_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepurchase',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='sitepurchase',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
    ]
