# Generated by Django 5.0.2 on 2024-04-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0041_remove_sitepurchase_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepurchase',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
