# Generated by Django 5.0.2 on 2024-04-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0042_alter_sitepurchase_duration_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitepurchase',
            name='duration_days',
            field=models.IntegerField(default=1),
        ),
    ]
