# Generated by Django 5.0.2 on 2024-04-09 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0043_alter_sitepurchase_duration_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offername', models.CharField(max_length=500)),
                ('offerprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('offerdiscount', models.IntegerField()),
                ('offerdescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Developer_Name', models.CharField(max_length=200)),
                ('Developer_Photo', models.ImageField(upload_to='Developer_images/')),
                ('Developer_Skill', models.CharField(max_length=200)),
                ('About_Developer', models.TextField()),
                ('GitHub', models.URLField(help_text='Github URL ')),
                ('Facebook', models.URLField(help_text='Facebook Page URL')),
                ('LinkedIn', models.URLField(help_text='LinkedIn Profile URL')),
                ('Instagram', models.URLField(help_text='Instagram Profile URL')),
            ],
        ),
    ]
