# Generated by Django 5.0.2 on 2024-04-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0044_offers_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='LinkedIn',
        ),
        migrations.AddField(
            model_name='team',
            name='Twitter',
            field=models.URLField(default=2, help_text='Twitter Profile URL'),
            preserve_default=False,
        ),
    ]
