# Generated by Django 5.0.2 on 2024-04-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0045_remove_team_linkedin_team_twitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Co_Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('founder_image', models.ImageField(upload_to='FounderImge/')),
                ('Position', models.CharField(max_length=200)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='team',
            name='Twitter',
            field=models.URLField(help_text='Twitter Profile URL', null=True),
        ),
    ]
