# Generated by Django 5.0.2 on 2024-04-14 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0046_co_founder_alter_team_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertising',
            options={'verbose_name_plural': 'Advertising'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Category'},
        ),
        migrations.AlterModelOptions(
            name='co_founder',
            options={'verbose_name_plural': 'Co Founder'},
        ),
        migrations.AlterModelOptions(
            name='deploye',
            options={'verbose_name_plural': 'Deploye Request'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name_plural': 'Hospital'},
        ),
        migrations.AlterModelOptions(
            name='offers',
            options={'verbose_name_plural': 'Offers'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name_plural': 'Portfolio'},
        ),
        migrations.AlterModelOptions(
            name='sitepurchase',
            options={'verbose_name_plural': 'SitePurchase'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name_plural': 'Our Team'},
        ),
    ]
