# Generated by Django 5.0.2 on 2024-04-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0049_alter_sitepurchase_options_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='offers',
            name='offerimage',
            field=models.ImageField(null=True, upload_to='offers/'),
        ),
    ]
