# Generated by Django 5.0.2 on 2024-04-17 17:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0050_offers_offerimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertising',
            name='beautiful_design',
            field=models.TextField(help_text='Write About Beautiful Design'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='brand_strategy',
            field=models.TextField(help_text='Write About Your Strategy'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='description_1',
            field=models.TextField(help_text='Description for  Project 1'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='description_2',
            field=models.TextField(help_text='Description for  Project 2'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='description_3',
            field=models.TextField(help_text='Description for  Project 3'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='description_4',
            field=models.TextField(help_text='Description for  Project 4'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image1',
            field=models.ImageField(help_text='Image1 For Slider In Hero Section', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image2',
            field=models.ImageField(help_text='Image2 For Slider In Hero Section', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='image3',
            field=models.ImageField(help_text='Image3 For Slider In Hero Section', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic1',
            field=models.ImageField(help_text='About Us Image For Section', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic2',
            field=models.ImageField(help_text='About Us Image For Section', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic_1',
            field=models.ImageField(help_text='Picture for  Project 1', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic_2',
            field=models.ImageField(help_text='Picture for  Project 2', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic_3',
            field=models.ImageField(help_text='Picture for  Project 3', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='pic_4',
            field=models.ImageField(help_text='Picture for  Project 4', upload_to='Advertising/'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='product_experience',
            field=models.TextField(help_text='Write About Product Experience'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='short_Discription',
            field=models.CharField(help_text='Short Intro  In Hero Section', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='short_about_us',
            field=models.TextField(help_text='Short Intero In Hero Section'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='short_about_us2',
            field=models.TextField(help_text='Write About Us Info', null=True),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='time_management',
            field=models.TextField(help_text='Write About Time Management'),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title_1',
            field=models.CharField(help_text='Title for  Project 1', max_length=255),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title_2',
            field=models.CharField(help_text='Title for  Project 2', max_length=255),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title_3',
            field=models.CharField(help_text='Title for  Project 3', max_length=255),
        ),
        migrations.AlterField(
            model_name='advertising',
            name='title_4',
            field=models.CharField(help_text='Title for  Project 4', max_length=255),
        ),
        migrations.CreateModel(
            name='UserMonitering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=45)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
