# Generated by Django 5.0.2 on 2024-04-18 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0051_alter_advertising_beautiful_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitering',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
