# Generated by Django 5.0.2 on 2024-04-20 19:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0053_testimonial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Laboratory_Video',
        ),
        migrations.AlterField(
            model_name='profile',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default='https://res.cloudinary.com/dm9eqnawe/image/upload/v1/media/profilepic/avatar_wtgsf3', null=True, upload_to='profilepic/'),
        ),
    ]
