# Generated by Django 5.0.2 on 2024-04-21 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0054_remove_hospital_laboratory_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitering',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DynamicGenerator.profile'),
        ),
    ]
