# Generated by Django 5.0.2 on 2024-04-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0056_sitepurchase_expire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitepurchase',
            name='expire',
        ),
        migrations.AddField(
            model_name='sitepurchase',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
