# Generated by Django 5.0.2 on 2024-04-26 06:33

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0057_remove_sitepurchase_expire_sitepurchase_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploye',
            name='sitefile',
            field=models.FileField(storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(), upload_to='fordeployesites'),
        ),
    ]
