# Generated by Django 5.0.2 on 2024-04-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DynamicGenerator', '0059_remove_usermonitering_restricted'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermonitering',
            name='restricted',
            field=models.BooleanField(default=False),
        ),
    ]
